before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.electron
    - docker.latest
    - docker.tmp
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: rlo+xG5XlwNv0AmDUjSCpDWiEVWBFU4fM0ojAV2bSplHUkCNzfWeN7zF3+uyquHNKkvxF9fQ030n1hn0PfNAOKimqAT/BAwMtdR34dF1UsyezqLOkH1jjhPD4RUZhHVdLM9Xua/4axeIBt9aO9g01ZpUgI3imAN8Xrtvf7UjeAUIf+BK/omtNumEh8HXWQy0Ob1FtSjG5Bh2W+O2vr2PL/D4P9cwJNwsZg6ikx6thnoDNHWXynXwY+YgkBmx0SR7MthiWFblYQM+eYkGHBKLy8ISRh3SFspccZucygjd96J53q9znrQxG1stSUAl3LSRs76cYooFZKD9gWR5UUZUCaqW5w2qrB42fogx1IndDW5F0abwAYb9h/yTvpHD2tFPRgLgRZJoRjVSAu8Wnq5WIYtRc/ngwwKJGGOEwr1UYYBsEpUhYgyCkMwhPbT6XsSrOP60Kx1L8hyMhfOaEppCreQlxNrbzoczI/GY9CHJPP4E64Qc/LVyOmPk6GMhr4/tmR1VoNbKLwoie5iG9P8fX76BBqnUZ6vWDxdTw+C84ridFbpQrJfQx5AjQl61m60WxnFoN+adTDy/FrFI87BxyUYipyG7R2MVNbfkqT1KPgCnZ+yC5wKPoE3dq4vurP6fnrUdT4FlvW0c3L40fvR5LWsthp+RhS+cany25DIxl1E= # CRYPTO_AES_KEY
language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
